language: scala

scala:
   - 2.10.6
   - 2.11.7

jdk:
   - openjdk7
   - oraclejdk7
   - oraclejdk8

matrix:
  include:
    - scala: 2.12.1
      jdk: oraclejdk8
      env:
        - TRAVIS_NODE_VERSION="4"
    - scala: 2.12.1
      jdk: oraclejdk8
      env:
        - TRAVIS_NODE_VERSION="6"

env:
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="6"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - which node

branches:
  except:
    - /^wip-.*$/

# small tricks to enable faster builds

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
   - $HOME/.nvm

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

script:
  # Your normal script
  - sbt ++$TRAVIS_SCALA_VERSION test:compile test:fastOptJS
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - bash <(curl -s https://codecov.io/bash)
