language: scala

scala:
   - "2.10.6"
   - "2.11.7"

jdk:
   - oraclejdk7
   - openjdk7
   - oraclejdk8

branches:
  except:
    - /^wip-.*$/

# small tricks to enable faster builds

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  # Your normal script
  - sbt -J-XX:ReservedCodeCacheSize=256M test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - bash <(curl -s https://codecov.io/bash)
